"""Accessibility utilities for Tailwind CSS"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/utilities/accessibility.ipynb.

# %% auto 0
__all__ = ['FORCED_COLOR_ADJUST_VALUES', 'forced_color_adjust', 'test_accessibility_forced_color_adjust_examples',
           'test_accessibility_screen_reader_examples', 'test_accessibility_practical_examples',
           'test_accessibility_factory_documentation', 'visually_hidden', 'high_contrast_safe',
           'test_accessibility_helper_examples']

# %% ../../nbs/utilities/accessibility.ipynb 3
from typing import Dict, Any
from cjm_fasthtml_tailwind.core.base import (
    SingleValueFactory, combine_classes
)
from ..builders.scales import SimpleFactory

# %% ../../nbs/utilities/accessibility.ipynb 5
# Forced color adjust utilities
FORCED_COLOR_ADJUST_VALUES = {
    "auto": "forced-color-adjust-auto",
    "none": "forced-color-adjust-none"
}

# Create forced color adjust factory
forced_color_adjust = SimpleFactory(
    FORCED_COLOR_ADJUST_VALUES, 
    "Forced color adjust utilities for opting in and out of forced colors (e.g., Windows High Contrast Mode)"
) # The forced color adjust factory

# %% ../../nbs/utilities/accessibility.ipynb 6
def test_accessibility_forced_color_adjust_examples(
):
    """Test forced color adjust utilities."""
    # Test forced color adjust utilities with dot notation
    assert str(forced_color_adjust.auto) == "forced-color-adjust-auto"
    assert str(forced_color_adjust.none) == "forced-color-adjust-none"

# Run the tests
test_accessibility_forced_color_adjust_examples()

# %% ../../nbs/utilities/accessibility.ipynb 8
# Import screen reader utilities from layout module
from .layout import sr_only, not_sr_only

# %% ../../nbs/utilities/accessibility.ipynb 9
def test_accessibility_screen_reader_examples(
):
    """Test screen reader utilities imported from layout module."""
    # Test screen reader utilities
    assert str(sr_only) == "sr-only"
    assert str(not_sr_only) == "not-sr-only"

# Run the tests
test_accessibility_screen_reader_examples()

# %% ../../nbs/utilities/accessibility.ipynb 11
def test_accessibility_practical_examples(
):
    """Test accessibility utilities in practical FastHTML component examples."""
    from fasthtml.common import Div, Button, Span, Input, Label, Nav, A
    
    # Skip link for keyboard navigation
    skip_link = A(
        "Skip to main content",
        href="#main-content",
        cls=combine_classes(
            sr_only,
            "focus:not-sr-only",
            "focus:absolute",
            "focus:top-4",
            "focus:left-4",
            "bg-white",
            "p-2",
            "rounded"
        )
    )
    assert "sr-only" in skip_link.attrs['class']
    assert "focus:not-sr-only" in skip_link.attrs['class']
    
    # Form with screen reader only label
    form_field = Div(
        Label("Search", cls=str(sr_only), for_="search"),
        Input(
            type="search",
            id="search",
            placeholder="Search...",
            cls="w-full px-4 py-2 border rounded"
        )
    )
    assert form_field.children[0].attrs['class'] == "sr-only"
    
    # Icon button with screen reader text
    icon_button = Button(
        # Icon would go here (e.g., SVG)
        Span("Close dialog", cls=str(sr_only)),
        cls="p-2 rounded hover:bg-gray-100",
        aria_label="Close dialog"
    )
    assert icon_button.children[0].attrs['class'] == "sr-only"
    
    # Navigation with forced color adjustments
    high_contrast_nav = Nav(
        A("Home", href="/", cls=combine_classes(forced_color_adjust.none, "text-blue-600")),
        A("About", href="/about", cls=combine_classes(forced_color_adjust.none, "text-blue-600")),
        A("Contact", href="/contact", cls=combine_classes(forced_color_adjust.none, "text-blue-600")),
        cls=combine_classes(forced_color_adjust.auto, "flex gap-4")
    )
    assert high_contrast_nav.attrs['class'] == "forced-color-adjust-auto flex gap-4"
    assert "forced-color-adjust-none" in high_contrast_nav.children[0].attrs['class']
    
    # Loading spinner with screen reader text
    loading_spinner = Div(
        Div(cls="animate-spin h-5 w-5 border-2 border-gray-900 rounded-full border-t-transparent"),
        Span("Loading...", cls=str(sr_only)),
        cls="inline-flex items-center"
    )
    assert loading_spinner.children[1].attrs['class'] == "sr-only"

# Run the tests
test_accessibility_practical_examples()

# %% ../../nbs/utilities/accessibility.ipynb 12
def test_accessibility_factory_documentation(
):
    """Test that factories have accessible documentation."""
    # Test factory documentation
    assert forced_color_adjust.describe() == "Forced color adjust utilities for opting in and out of forced colors (e.g., Windows High Contrast Mode)"
    
    # Test SingleValueFactory documentation for imported utilities
    assert sr_only.describe() == "Hide element visually but keep it available to screen readers"
    assert not_sr_only.describe() == "Undo sr-only, making element visible again"
    
    # Test get_info method
    info = forced_color_adjust.get_info()
    assert info['description'] == "Forced color adjust utilities for opting in and out of forced colors (e.g., Windows High Contrast Mode)"
    assert 'available_values' in info['options']
    assert 'auto' in info['options']['available_values']
    assert 'none' in info['options']['available_values']

# Run the tests
test_accessibility_factory_documentation()

# %% ../../nbs/utilities/accessibility.ipynb 14
def visually_hidden(
    focusable: bool = False  # Whether the element should be visible when focused
) -> str:  # CSS classes for hiding element visually
    """
    Hide an element visually but keep it available to screen readers.
    
    Args:
        focusable: If True, element becomes visible when focused (useful for skip links)
    
    Returns:
        CSS classes for visual hiding with optional focus visibility
    """
    if focusable:
        return combine_classes(sr_only, "focus:not-sr-only")
    return str(sr_only)

# %% ../../nbs/utilities/accessibility.ipynb 15
def high_contrast_safe(
    *classes: str  # Additional CSS classes to combine
) -> str:  # CSS classes including forced color adjust
    """
    Create classes that work well with high contrast mode.
    
    Args:
        *classes: Additional CSS classes to include
    
    Returns:
        Combined CSS classes with forced-color-adjust-auto
    """
    return combine_classes(forced_color_adjust.auto, *classes)

# %% ../../nbs/utilities/accessibility.ipynb 16
def test_accessibility_helper_examples(
):
    """Test helper functions for common accessibility patterns."""
    # Test visually_hidden helper
    assert visually_hidden() == "sr-only"
    assert visually_hidden(focusable=True) == "sr-only focus:not-sr-only"
    
    # Test high_contrast_safe helper
    assert high_contrast_safe() == "forced-color-adjust-auto"
    assert high_contrast_safe("bg-blue-500", "text-white") == "forced-color-adjust-auto bg-blue-500 text-white"

# Run the tests
test_accessibility_helper_examples()
